name: Django CI. # Workflow name

on:
  push:   # run the workflow when code pushed to main
    branches:
      - master

  pull_request:  # run CI when somebody creates/updates a pull request targeting main
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest #runner

    services:
        postgres:
            image: postgres:18

            env:
              POSTGRES_DB: test_db
              POSTGRES_USER: resil
              POSTGRES_PASSWORD: password
            
            ports:
              - 5432:5432
            
            options: >-
                --health-cmd="pg_isready -U postgres -d test_db"
                --health-interval=10s
                --health-timeout=5s
                --health-retries=5

    steps:

      - name: Checkout code
        uses: actions/checkout@v4 # download the Repository into the runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run django checks
        env:
          DBNAME: test_db
          DBUSER: resil
          DBPASSWORD: password
          DBHOST: localhost
          DBPORT: 5432

  
        run: |
          python manage.py check

      - name: Run tests
        env:
          DBNAME: test_db
          DBUSER: resil
          DBPASSWORD: password
          DBHOST: localhost
          DBPORT: 5432
        run: |
          python manage.py test
        
      - name: Build Docker Image
        run: |
            docker build -t pollapp:ci .
