name: Django CI. # Workflow name

on:
  push:   # run the workflow when code pushed to main
    branches:
      - master

  pull_request:  # run CI when somebody creates/updates a pull request targeting main
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest #runner
    steps:

      - name: Checkout code
        uses: actions/checkout@v4 # download the Repository into the runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create a Docker Network
        run: |
          docker network create pollapp-network
      
      - name: Start the Postgres
        run: |
          docker run \
            -d \
            --name postgres \
            --network pollapp-network \
            -e POSTGRES_DB=test_db \
            -e POSTGRES_USER=resil \
            -e POSTGRES_PASSWORD=password \
            -p 5432:5432 \
            postgres:18
      
      - name: Wait for the postgres
        run: |
          for i in {1..30}; do
            if docker exec postgres pg_isready -U postgres -d test_db; then
              echo "DB is Ready"
              break
            fi

            echo "Wiating for DB"
            sleep 2
          done
      
      - name: Run django checks
        env:
          DBNAME: test_db
          DBUSER: resil
          DBPASSWORD: password
          DBHOST: localhost
          DBPORT: 5432

  
        run: |
          python manage.py check

      - name: Run tests
        env:
          DBNAME: test_db
          DBUSER: resil
          DBPASSWORD: password
          DBHOST: localhost
          DBPORT: 5432
        run: |
          python manage.py test
        
      - name: Build Docker Image
        run: |
            docker build -t pollapp:ci .
      - name: Run Django Container
        env:
          DBNAME: test_db
          DBUSER: resil
          DBPASSWORD: password
          DBHOST: localhost
          DBPORT: 5432
        run: |
            docker run \
              -d \
               --name pollapp \
              --network pollapp-network \
              -p 8000:8000 \
              -e DBNAME \
              -e DBUSER \
              -e DBPASSWORD \
              -e DBHOST \
              -e DBPORT \
              pollapp:ci
      - name : Check Container
        run: |
            docker ps

      - name: Show Django container logs
        run: |
            docker logs pollapp
      
      - name: Health Check
        run: |
          curl --fail http://localhost:8000/
      
      - name: Check Postgres
        if: failure()
        run: |
          docker logs postgres